[[symbols]]
name = "FAKEPACA"
subscribe_trades = true
subscribe_bars = true
aggregation_interval_hours = 24

[database]
host = "mariadb-koqv.sliplane.app"
port = 3306
userroot = "root"
user = "dbuser"
database = "db"
